services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak-flightbook
    ports:
      - "8180:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-realm-export.json:/opt/keycloak/data/import/flightbook-realm.json
    command: start-dev --import-realm

  flightbook:
    build: ./java-rest-server
    image: registry.infres.fr/flightbook
    container_name: flightbook-app
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/flightbook/protocol/openid-connect/certs
      KEYCLOAK_ISSUER: http://localhost:8180/realms/flightbook
    depends_on:
      - keycloak
